name: ai-tests
on:
  push:
    paths: ["apps/ai/**", ".github/workflows/ai-tests.yml"]
  pull_request:
    paths: ["apps/ai/**", ".github/workflows/ai-tests.yml"]

jobs:
  ai-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pip install "poetry==2.1.3"

      - name: Install deps (no dev)
        working-directory: apps/ai
        run: poetry install --no-interaction --no-ansi

      - name: Install dev deps (pytest)
        working-directory: apps/ai
        run: poetry install --with dev --no-interaction --no-ansi

      - name: Run tests
        working-directory: apps/ai
        run: poetry run pytest -q
